README.md
client/.lintstagedrc.json
client/src/components/vote.tsx
client/src/constants.ts
client/src/pages/model/detail.tsx
client/src/pages/script/register.tsx
client/src/pages/upload-creator.tsx
client/src/queries/graphql.ts
script-examples/alpaca/.lintstagedrc.json
script-examples/alpaca/config.json
script-examples/alpaca/src/alpaca.ts
script-examples/kandinsky/.lintstagedrc.json
script-examples/kandinsky/config.json
script-examples/kandinsky/src/kandinsky.ts

Feat#110 data cleaning

---

client/.lintstagedrc.json
client/src/components/navbar.tsx
client/src/components/navigation-menu.tsx
client/src/pages/curators.tsx
client/src/styles/ui.css
script-examples/alpaca/.lintstagedrc.json
script-examples/kandinsky/.lintstagedrc.json

Closes #131 
Also fixes some ui navbar issues, and some pre-commit lintint errors

Fix#131 fix large screen UI on upload screens

---

client/src/components/choose-operator.tsx
client/src/queries/graphql.ts

Fix#140 selection of operators with strange behaviour

---

script-examples/alpaca/config.json
script-examples/alpaca/src/alpaca.ts
script-examples/kandinsky/config.json
script-examples/kandinsky/src/kandinsky.ts

fix: checking user payments against the request operator instead of the running one

---

client/src/components/choose-operator.tsx
client/src/components/choose-script.tsx

Fix#146 choose scripts and operators issues

---

client/src/components/basic-table.tsx
client/src/components/choose-operator.tsx
client/src/components/choose-script.tsx
client/src/utils/operator.ts

Also fixes:
* fix choose script and choose operators loading

feat: refactor choose script code to not show scripts without operators;

---

client/src/components/conversations.tsx
client/src/components/debounce-button.tsx
client/src/components/debounce-icon-button.tsx
client/src/components/debounce-loading-button.tsx
client/src/components/fund-dialog.tsx
client/src/components/stepper.tsx
client/src/components/vote.tsx
client/src/guards/script-fee.tsx
client/src/pages/curators.tsx
client/src/pages/model/chat.tsx
client/src/pages/upload-creator.tsx

Feat#149 prevent double clicks on buttons

---

client/src/components/choose-operator.tsx
client/src/components/choose-script.tsx
client/src/components/conversations.tsx
client/src/components/get-icon.tsx
client/src/components/layout.tsx
client/src/components/profile-menu.tsx
client/src/components/stepper.tsx
client/src/components/vote.tsx
client/src/constants.ts
client/src/context/wallet.tsx
client/src/guards/script-fee.tsx
client/src/main.tsx
client/src/pages/home.tsx
client/src/pages/operators.tsx
client/src/pages/registrations.tsx
client/src/pages/script/register.tsx
client/src/queries/graphql.ts
client/src/utils/common.ts
client/src/utils/operator.ts
documents/tags.md

Feat#116 operations cancellation

---

client/src/components/choose-operator.tsx
client/src/components/choose-script.tsx
client/src/components/conversations.tsx
client/src/components/navbar.tsx
client/src/pages/home.tsx
client/src/queries/graphql.ts
client/src/utils/arweave.ts
client/src/utils/common.ts

fix search problems across the application

---

client/src/components/layout.tsx
client/src/constants.ts
client/src/guards/fund-bundlr.tsx
client/src/main.tsx
client/src/pages/model/chat.tsx
client/src/root.tsx

Feat#192 make all txs from users dispatches

---

client/src/components/conversations.tsx
client/src/pages/model/chat.tsx

fix: add scroll to conversations list when there are too many; ui improvements in chat page

---

client/src/constants.ts
help-scripts/src/pay.ts
script-examples/MusicGen/src/constants.ts
script-examples/alpaca/src/constants.ts
script-examples/kandinsky/src/constants.ts

refactor: update "u" contract address constant

---

client/src/constants.ts

feat: align application fees and update app version to v0.3

---

client/src/components/navbar.tsx
client/src/components/stepper.tsx
client/src/components/swap-u.tsx
client/src/constants.ts
client/src/pages/curators.tsx
client/src/pages/model/chat.tsx
client/src/pages/operators.tsx
client/src/pages/script/register.tsx
client/src/pages/upload-creator.tsx
client/src/utils/operator.ts
client/src/utils/u.ts
script-examples/dreamshaper/config.json
script-examples/dreamshaper/package.json
script-examples/dreamshaper/src/dreamshaper.ts
script-examples/dreamshaper/src/inference-cpu.py
script-examples/dreamshaper/src/inference.py

Feat#211 change ar references to u & bugfixes

---

client/src/components/choose-operator.tsx
client/src/components/script-card.tsx

fix: choose opeerator, and operators count for each script filtering by script transaction

---

client/src/components/choose-script.tsx
client/src/constants.ts
client/src/pages/operators.tsx
client/src/utils/script.ts
help-scripts/.gitignore
help-scripts/package.json
help-scripts/src/fake-delete.ts

Feat#212 allow script deletions

---

client/package.json
client/src/components/basic-table.tsx
client/src/components/choose-operator.tsx
client/src/components/choose-script.tsx
client/src/components/operator-row.tsx
client/src/components/script-card.tsx
client/src/components/script-row.tsx
client/src/components/select-control.tsx
client/src/constants.ts
client/src/pages/curators.tsx
client/src/pages/model/detail.tsx
client/src/pages/operators.tsx
client/src/pages/script/script.tsx
client/src/utils/apollo.ts
client/src/utils/common.ts
client/src/utils/operator.ts
client/src/utils/script.ts
help-scripts/src/fake-delete.ts

Feat#213 allow script updates

---

script-examples/dreamshaper/src/dreamshaper.ts

* also add more logging
Closes #221

fix: script ignoring scripts with previous fails

---

client/src/components/choose-operator.tsx
client/src/main.tsx
client/src/pages/model/change-operator.tsx

fix: change operator in chat not working

---

client/src/components/choose-operator.tsx
client/src/components/choose-script.tsx
client/src/pages/model/detail.tsx

feat: automatically choose script and operator if there are only one

---

script-examples/dreamshaper/src/dreamshaper.ts

* fix: fixes script incorrectly storing successfully proccessed txs, add logging

Fix#229 script failing to answer transactions sometimes

---

client/src/utils/script.ts

* fixes scripts incorrectly filtering old versions
Closes #231

fix#231 bug when updating scripts after deploy

---

client/src/components/message-footer.tsx
client/src/utils/common.ts

Fix#246 filtering deleted scripts code using wrong tags

---

client/src/constants.ts
client/src/pages/model/chat.tsx
client/src/utils/operator.ts

Feat#259 update chat queries to also use new atomic token tags

---

client/src/components/choose-script.tsx
client/src/utils/script.ts

fix: filter script payments for same script tx

---

client/src/queries/graphql.ts
client/src/utils/operator.ts

fix: add owner field to contracts query, add missing protection when checking for script operators

---

client/src/components/message-footer.tsx
client/src/context/wallet.tsx
client/src/pages/model/chat.tsx
client/src/utils/u.ts

Closes #291 
Also: 
* update u dre node
* small fix using async /await in non-promise function

fix: arconnect always disabled

---

client/src/constants.ts
client/src/pages/model/chat.tsx

feat: add Transaction-Origin tag with ui value to ui app requests

---

client/src/components/navbar.tsx
client/src/context/wallet.tsx
client/src/hooks/usePollingEffect.tsx

fix: polling current selected balance

---

client/src/pages/model/chat.tsx

fix: prevent multiple consecutive clicks from sending message more than once

---

client/src/components/message-footer.tsx
client/src/hooks/useTimeInterval.tsx

fix: show only 'a few seconds ago' before one minute and update time every minute

---

client/src/utils/operator.ts

Feat#274 consider all payments to list operators

---

client/src/utils/operator.ts

fix: accessing wrong property in filtering operator requests

---

client/src/pages/model/detail.tsx
client/src/pages/operator/operator-details.tsx
client/src/pages/script/script-details.tsx

feat: remove like system

---

client/src/pages/model/chat.tsx

feat: add multi line to chat input

---

client/src/components/configuration.tsx
client/src/components/conversations.tsx
client/src/components/trade.tsx
client/src/constants.ts
client/src/pages/model/chat.tsx

Feat#319 customisable asset name on marketplace

---

client/src/utils/ucm.ts

fix: add right evaluation options when connecting to atomic assets contracts

---

client/src/constants.ts

feat: update payment percentages

---

client/package.json
client/src/constants.ts
client/src/pages/model/chat.tsx
client/src/utils/operator.ts

feat: implement prompt txs as atomic assets

---

client/package.json
client/src/components/ai-list-card.tsx
client/src/pages/home.tsx
client/src/pages/model/chat.tsx
client/src/pages/model/detail.tsx
client/src/utils/common.ts

Fix#346 bug fixes on marketplace

---

client/src/components/configuration.tsx
client/src/components/navbar.tsx
client/src/components/operator-row.tsx
client/src/constants.ts
client/src/pages/model/chat.tsx
client/src/pages/model/detail.tsx
client/src/pages/sign-in.tsx
client/src/utils/u.ts

Feat#341 show prices in usd

---

client/src/components/navbar.tsx
client/src/pages/model/chat.tsx
client/src/pages/sign-in.tsx

fix: small issues

---

client/src/components/get-icon.tsx
client/src/components/profile-menu.tsx
client/src/main.tsx
client/src/pages/terms.tsx

Feat# terms and conditions page

---

client/src/constants.ts
client/src/pages/sign-in.tsx

Fix#362 change creation of wallet link

---

client/src/components/navbar.tsx
client/src/styles/components.tsx

Feat#371 allow copy address on marketplace

---

client/src/components/message-detail.tsx
client/src/components/message.tsx
client/src/utils/pst.ts

Feat#378 add download button

---

client/src/pages/model/chat.tsx

fix: wrong default number of images in configuration

---

client/src/pages/model/chat.tsx

fix: prompt cost validations not checkin gfor full price

---

client/src/components/message.tsx
client/src/components/pending-card.tsx
client/src/constants.ts
client/src/pages/model/chat.tsx

feat: update links to view transactions

---

client/src/components/configuration.tsx
client/src/pages/model/chat.tsx

fix: properly passing royalty in request tags, update configuration reset flow

---

client/src/constants.ts
client/src/pages/sign-in.tsx

feat: add specific link to buy ar for us

---

client/src/components/configuration.tsx
client/src/pages/model/chat.tsx

feat: change atomic asset configration options to radio buttons

---

client/src/components/chat-content.tsx
client/src/components/message-display.tsx
client/src/context/theme.tsx
client/src/hooks/useRequests.tsx
client/src/hooks/useResponses.tsx
client/src/hooks/useScroll.tsx
client/src/hooks/useScrollLock.tsx
client/src/pages/model/chat.tsx
client/src/pages/sign-in.tsx

Closes #399 
Closes #379 
Closes #314

Fix#399 messages disappearing on UI

---

client/package.json
client/src/components/choose-operator.tsx
client/src/components/choose-script.tsx
client/src/hooks/useModels.tsx
client/src/hooks/useRequests.tsx
client/src/hooks/useResponses.tsx
client/src/pages/sign-in.tsx
client/src/utils/arweave.ts

Feat#394 choose an available operator

---

client/src/components/ai-card.tsx
client/src/components/ai-list-card.tsx
client/src/components/featured.tsx
client/src/hooks/useModels.tsx
client/src/pages/home.tsx
client/src/pages/sign-in.tsx

Closes #413 
Also fixes models flickering on home screen

Fix#413 photon model without image

---

client/src/components/message.tsx
client/src/components/trade.tsx

feat: refactor trade sliders to be percentages to better handle trading fracitons

---

client/src/components/layout.tsx

fix: height not correct when warning message shown, resulting in scroll not loading next items

---

client/src/components/layout.tsx
client/src/components/message-display.tsx
client/src/components/navbar.tsx
client/src/constants.ts
client/src/guards/wallet.tsx
client/src/hooks/useComponentDimensions.tsx
client/src/styles/main.css

Fix#408 onboarding screen always popping up

---

client/package.json
client/src/pages/model/chat.tsx

Fix#409 first message failing

---

client/src/hooks/useRequests.tsx
client/src/pages/model/chat.tsx

Fix#424 users seeing messages from other users

---

client/src/components/featured.tsx
client/src/components/list-loading-card.tsx
client/src/components/loading-card.tsx
client/src/constants.ts
client/src/hooks/useFeaturedModels.tsx
client/src/pages/home.tsx

Feat#417 filter models by category

---

client/src/constants.ts
client/src/hooks/useFeaturedModels.tsx
client/src/hooks/useModels.tsx
client/src/pages/history.tsx
client/src/pages/model/detail.tsx
client/src/pages/script/script-details.tsx
client/src/tests/pages/model/detail.test.tsx
documents/tags.md

Fix#428 model category tag filter

---

client/src/components/conversations.tsx
client/src/components/trade.tsx
client/src/utils/ucm.ts

Fix#433 trade on bazar issues

---

client/index.html
client/package.json
client/src/components/message.tsx

Feat#290 allow sharing inferences on twitter

---

client/src/components/user-feedback.tsx
client/src/constants.ts
client/src/context/user-feedback.tsx
client/src/hooks/useRatingFeedback.tsx
client/src/pages/model/chat.tsx
client/src/root.tsx

Feat#447 show rating and feedback popup for active users

---

client/src/components/configuration.tsx
client/src/components/license-configuration.tsx
client/src/interfaces/common.ts
client/src/pages/model/chat.tsx

* refactor configuration to use form controls;
* allow configuration to be saved between reloads

feat#411: Mantain prompt settings between reloads 

---

client/src/components/chat-content.tsx
client/src/components/message.tsx
client/src/constants.ts
client/src/interfaces/common.ts
client/src/pages/model/chat.tsx

Feat#423 copy settings

---

client/src/components/configuration.tsx
client/src/components/layout.tsx
client/src/components/message-display.tsx
client/src/components/message-footer.tsx
client/src/components/message.tsx
client/src/interfaces/common.ts
client/src/pages/model/chat.tsx

Feat#462 multiple image sizes marketplace

---

client/src/pages/model/chat.tsx

fix: not properly detecting config changes

---

client/src/components/navbar.tsx
client/src/main.tsx
client/src/pages/browse-arbitrum-requests.tsx
client/src/pages/request-arbitrum-update.tsx

feat: arbitrum phase 2

---

client/src/pages/browse-arbitrum-requests.tsx
client/src/pages/request-arbitrum-update.tsx

Feat#521 arbitrum phase 2 keeplink does not store the value

---

client/src/components/request-allowance.tsx

fix: properly setting amount to fund background wallet
